services:
  - type: web
    name: youtube-learning-manager-backend
    runtime: ruby
    buildCommand: "bundle install; bundle exec rake db:migrate"
    startCommand: "bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-production}"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
    region: oregon
    plan: free
    rootDir: backend
